server {
    listen 80;
    server_name localhost;
    root /var/www/html/public; # Arahkan ke folder public Laravel


    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Ini bagian penting:
    # Teruskan request file .php ke service 'backend' (php-fpm)
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass backend:9000; # 'backend' adalah nama service di docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}